# Generated by Django 5.0.4 on 2025-04-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_advertisement_brand_color_colorimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCAccessories',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCFactoryWarrantyMonth',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCHsCode',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCImage1',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCImage2',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCImage3',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCItemFactoryCode',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCItemNameChina',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCItemNameEnglish',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCItemPadaanName',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCNote1',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCOneBoxGrossWeightKg',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCOneBoxHeight',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCOneBoxLength',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCOneBoxNetWeightKg',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCOneBoxVolumeM3',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCOneBoxWeight',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCOneTotalCBM',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCShopWarrantyMonth',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='TCUseInstructions',
        ),
    ]
