# Generated by Django 5.0.4 on 2025-04-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_infoproduct_tcaccessories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='TCIsView',
            field=models.BooleanField(default=False, help_text='Сайт дээр харуулах эсэх'),
        ),
    ]
