# Generated by Django 5.0.4 on 2025-04-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_metalrate_assay_alter_metalrate_metal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarespecification',
            name='detail',
            field=models.CharField(blank=True, help_text='Сорьц', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hardwarespecification',
            name='name',
            field=models.CharField(help_text='Грамм', max_length=255),
        ),
    ]
